version: '3'

services:
    myweb:
        build: ./php/
        container_name: myweb
        restart: always
        ports:
          - 80:80
        volumes:
          - ./php/src:/var/www/html

    mydb:
        build: ./mysql/
        container_name: mydb
        ports:
          - 3306:3306
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=genpassword
          - MYSQL_PASSWORD=genpassword
          - MYSQL_DATABASE=genpassword
        volumes:
          - mydb_data:/var/lib/mysql
          
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 8080:80
        environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=mydb

volumes:
  mydb_data: